### ISSUE TITLE
XWA Not launching on Lutris

### ISSUE THREAD

**Issue by LaserTron** [dhollinger/lutris_installers#1]
Hi,

XWA+XWAU202 installed in Lutris, but when it comes time to launch the game nothing happens. Here is what is output on the terminal.
```
Unable to load locale dir, translations won't work.
2020-12-03 22:49:39,693: Your version of python-magic is too old.
2020-12-03 22:49:39,830: Lutris 0.5.8
2020-12-03 22:49:39,830: Running Intel Mesa driver 20.1.8 on Mesa Intel(R) UHD Graphics 620 (KBL GT2) (0x5917)
2020-12-03 22:49:39,830: GPU: 8086:5917 1028:0823 (i915 drivers)
Exception ignored in: <function InputDevice.__del__ at 0x7f4401201550>
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 159, in __del__
    self.close()
  File "/usr/lib/python3.8/site-packages/evdev/device.py", line 304, in close
    super().close()
  File "/usr/lib/python3.8/site-packages/evdev/eventio_async.py", line 54, in close
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
Running gamemoderun /home/nick/.local/share/lutris/runners/wine/lutris-5.7-11-x86_64/bin/wine /home/nick/Games/star-wars-x-wing-alliance/drive_c/GOG Games/Star Wars - X-Wing Alliance/cmdow.exe /run /hid xwa.bat
Initial process has started with pid 38451
Start monitoring process.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Initial process has exited (return code: 0)
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object 'libgamemodeauto.so.0' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Monitored process exited.
All monitored processes have exited.
Exit with returncode 0
2020-12-03 22:49:54,259: Game still running (state: running)
2020-12-03 22:49:54,259: Stopping STAR WARS: X-Wing Alliance (wine)
```

**Comment by LaserTron** [comment]
Incidentally, I've been able to get XWAUCP 1.6 running on wine (using playonlinux and winetricks) but the XWAU2020 installer doesn't work. Did you do anything special to get it to install?

**Comment by dhollinger** [comment]
The installer installs .NET 4.6.1 as that is required for the new installer to work. 

As for the issue, when did you install it? I made a recent change to `xwa.bat` that fixed an issue. Since that fix was tied to a file that gets downloaded not the installer itself, it has to be manually updated.

**Comment by dhollinger** [comment]
Your xwa.bat should look like this: https://github.com/dhollinger/lutris_installers/blob/master/installers/xwa/xwa.bat

**Comment by LaserTron** [comment]
> As for the issue, when did you install it? I made a recent change to `xwa.bat` that fixed an issue. Since that fix was tied to a file that gets downloaded not the installer itself, it has to be manually updated.

I installed it last night (December 3 2020.) I checked `xwa.bat` and it's the same as the file on my system. Also Lutris does launch that file: I get the menu with Configure/Launch.

**Comment by LaserTron** [comment]
> The installer installs .NET 4.6.1 as that is required for the new installer to work.

I see. Actually on my wine installation, I did install dotnet461 with winetricks but the installation was messy and would hang. Winetricks says it's installed, but I wouldn't be surprised if it wasn't properly installed. I was actually impressed how smoothly it went on lutris.

**Comment by LaserTron** [comment]
Also another thing. I found that to get XWA to work in multiplater the `directplay` component needed to be installed.

**Comment by dhollinger** [comment]
I'll take care of installing directplay.

I would also suggest trying to uninstall/reinstall dotnet461, just to see if that helps. You're using the build-in Lutris Wine, right? I have not tested this with Proton or system WINE

**Comment by dhollinger** [comment]
Also, the game does crash without DXVK, so if you want to use XWAUpgrade, then you'll need DXVK + a GFX card and driver compatible with Vulkan.

The regular base game should work fine in just about any modern version of WINE, though.

**Comment by LaserTron** [comment]
> I'll take care of installing directplay.
> 
> I would also suggest trying to uninstall/reinstall dotnet461, just to see if that helps. You're using the build-in Lutris Wine, right? I have not tested this with Proton or system WINE

Including directplay would be awesome! Actually, I have tried stuff with proton, system wine, and lutris. Results vary. So for example I got dotnet461 and directplay installed on both system wine and proton. System wine works fine, I even played multiplayer over gameranger with a friend. The missing component was directplay.

I did the same with proton, but multiplayer still doesn't work.

Weirdly, the XWAU202 launcher worked in proton, but fails in system wine. The error message in system wine says something about dotnet, but winetricks says it's installed. Fun!

**Comment by LaserTron** [comment]
> Also, the game does crash without DXVK, so if you want to use XWAUpgrade, then you'll need DXVK + a GFX card and driver compatible with Vulkan.

Re: DVK, is this specific to XWAU2020? Because I've been able to get XWAU 1.6 running consistently.

**Comment by LaserTron** [comment]
BTW I just want to report some other behaviour in lutris:
1. When launching normally, which invokes `xwa.bat` and selecting configure, it fails.
2. When using _Run EXE inside wine prefix_, I'm able to launch Babu Friks Configurator.
3. When using  _Run EXE inside wine prefix_  to launch `Alliance.exe` it fails saying _XWingAlliance.exe was not found._
4. Using this method to launch `XWINGALLIANCE.EXE` results in a page fault and a dump.

**Comment by dhollinger** [comment]
> BTW I just want to report some other behaviour in lutris:
> 
> 1. When launching normally, which invokes `xwa.bat` and selecting configure, it fails.
Unfortunately, I haven't been able to reproduce this.
> 2. When using _Run EXE inside wine prefix_, I'm able to launch Babu Friks Configurator.
This is expected. All the `xwa.bat` does is provide a way for users to have a launcher that lets them choose launcher vs configurator.
> 3. When using  _Run EXE inside wine prefix_  to launch `Alliance.exe` it fails saying _XWingAlliance.exe was not found._
This is odd. Executing via `Alliance.exe` is specifically called out in the XWAUpgrade Documentation.
> 4. Using this method to launch `XWINGALLIANCE.EXE` results in a page fault and a dump.
The only time I run into this issue is when trying to run X-Wing Alliance + XWAUpgrade without DXVK enabled.


This is using the GOG installer, correct? I have not tested this with the Humble Bundle Installer, and I've had issues with getting XWAUpgrade to work in Lutris with the Steam version

**Comment by dhollinger** [comment]
> > Also, the game does crash without DXVK, so if you want to use XWAUpgrade, then you'll need DXVK + a GFX card and driver compatible with Vulkan.
> 
> Re: DVK, is this specific to XWAU2020? Because I've been able to get XWAU 1.6 running consistently.

Yes, DXVK is required for XWAU2020, not for XWAU 1.6, though I'm not sure how much longer they'll have that up for download

**Comment by LaserTron** [comment]
> Unfortunately, I haven't been able to reproduce this.

Maybe it's because we're using different distros. I'm using Manjaro. I think it may have to do with `gamemode`.


> > 1. Using this method to launch `XWINGALLIANCE.EXE` results in a page fault and a dump.
> 
> The only time I run into this issue is when trying to run X-Wing Alliance + 
XWAUpgrade without DXVK enabled.

I see. I did run the Lutris install script, so I guess it tried to enable DXVK. I should also add that my computer isn't that powerful. I've got an integrated grapics card: Intel UHD Graphics 620

> 
> This is using the GOG installer, correct? I have not tested this with the Humble Bundle Installer, and I've had issues with getting XWAUpgrade to work in Lutris with the Steam version

Yes I'm using the GOG installer. I'm starting to think that this isn't a problem with your script. I'm going to keep poking around.

**Comment by dhollinger** [comment]
> I see. I did run the Lutris install script, so I guess it tried to enable DXVK. I should also add that my computer isn't that powerful. I've got an integrated grapics card: Intel UHD Graphics 620

DXVK is managed by the installer and not Lutris. This is because of issues with the Babu Frik Configurator when DXVK is enabled. So It has to be turned on/off on a per .EXE basis and that can't be done using the Lutris DXVK option. Also, I'm not sure what the effect is with DXVK + Intel UHD Gfx chips. I'm on an NVidia card.
 
> > This is using the GOG installer, correct? I have not tested this with the Humble Bundle Installer, and I've had issues with getting XWAUpgrade to work in Lutris with the Steam version
> 
> Yes I'm using the GOG installer. I'm starting to think that this isn't a problem with your script. I'm going to keep poking around.

Let me know what you find :)
